# -*- coding: utf-8 -*-
"""Rayleigh Experiment v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lj6h_Ms3gcbcA5jsXz6hMKP92o--Ubtl
"""

# Commented out IPython magic to ensure Python compatibility.
from scipy import constants
from scipy.spatial import distance
from scipy.signal import savgol_filter
from multiprocessing import Process
from multiprocessing import Value
import tensorflow as tf
import numpy as np
import time

def task1(arg,x1):
    test = 100
    x1.value = test
    print(f"x = {x1.value}")
    
def task2(arg):
    print()
def task3(arg):
    print()


if __name__ == "__main__":
    ber = []
    x = []
    ber2 = []
    ber3 = []
    tests = 1

    start = time.time()
    for distance_to_bs in range(10, 30, 10):
      print(distance_to_bs)
      
      x1 = Value("d",0)
      
      processes = [Process(target=task1, args=(i,x1)) for i in range(1)]

      for process in processes:
        process.start()
      for process in processes:
        process.join()
        print('Done', flush=True)
      
    print(f"value: {x1.value}")  
    print("Execution time:",time.time()-start)

